### ISSUE TITLE
Generate visualisations based around Ransomware galaxy

### ISSUE THREAD

**Issue by StrayLightning** [Concinnity-Risks/LogisticalBudget#2]
Currently visualisations are all relating to Threat Actor activity.  It would be useful to add visualisation of events in the Ransomware galaxy.

**Comment by StrayLightning** [comment]
Commit 9d09a7a03e5e8f22ce5a16479ff63f0876cc993f added generation of scorecards for Ransomware galaxies.

**Comment by blackswanburst** [comment]
Thanks
