### ISSUE TITLE
APT Specific visualisations

### ISSUE THREAD

**Issue by blackswanburst** [Concinnity-Risks/LogisticalBudget#4]
Can we produce APT specific visualisations? Like something that shows me the number of events, urls, the number of netblocks associated, countries, and binaries? Basically if we want to profile a single APT in a visualisation, how might we do it?

**Comment by StrayLightning** [comment]
Commits in May and June to the current date have concentrated on generation of scorecards for comparing Threat Actors and Ransomewares.

**Comment by blackswanburst** [comment]
Looking great too!
