### ISSUE TITLE
Add a Periapt Systems Logo to the front page

### ISSUE THREAD

**Issue by blackswanburst** [Concinnity-Risks/LogisticalBudget#8]
@StrayLightning Can you write something about this being a collaborative effort at the bottom of the readme, and put your logo in there? I'm proud of your work, and want to make sure other people see that too.

**Comment by StrayLightning** [comment]
Added in commit 7339401ce68cf9a65a42e7e8c8d9f9d73db23e5a and commit 80d5d461f7be472bb7b3f34e55a9adde5549b975.  Closing.
